###Hello World
POST {{funcUrl}}/api/fn-hello-world?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bablu"
}

###Durable HTTP starter for delete Purview entities
POST {{funcUrl}}/api/orchestrators/fn-drbl-delete-purview-entities-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "accountName" : "azdemo103mfek9-pv101",
  "query": "sdfsdsf"   
}

###Durable HTTP starter for search Purview entities
POST {{funcUrl}}/api/orchestrators/fn-drbl-search-purview-entities-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "accountName" : "azdemo103mfek9-pv101",
  "query": "adworks",
  "limit": 10   
}

###Durable HTTP starter for SQL dedicated pool pause
POST {{funcUrl}}/api/orchestrators/fn-drbl-pause-sql-dp-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId" : "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e" 
}


###Get SQL Dedicated Pool
POST {{funcUrl}}/api/fn-get-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Pause SQL Dedicated Pool
POST {{funcUrl}}/api/fn-pause-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Resume SQL Dedicated Pool
POST {{funcUrl}}/api/fn-resume-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Publish Event Grid Event
POST {{eventGridUrl}}/api/events?overload=EventGridEvent&api-version=2018-01-01 HTTP/1.1
aeg-sas-key: {{eventGridKey}}
Content-Type: application/json

[
  {
    "id": "b3ccc7e3-c1cb-49bf-b7c8-0d4e60980616",
    "subject": "TestSubject",
    "data": {
      "Property1": "Value1",
      "Property2": "Value2"
    },
    "eventType": "Microsoft.Contoso.TestEvent",
    "eventTime": "2017-12-04T22:06:09.147165Z",
    "dataVersion": "1.0"
  }
]