###Hello World
POST {{funcUrl}}/api/fn-hello-world?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bablu"
}

###Add AD Owner
POST {{funcUrl}}/api/fn-add-ad-group-owner?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
    "groupId": "25a3d1d1-321a-42e8-a5fb-68e9ee653634",
    "ownerId": "879dd507-9e19-43ca-b3f7-495290d63910"
}

###List AD users
POST {{funcUrl}}/api/fn-list-ad-users?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
    "upnList": ["v-jphil", "v-balawrence","blawrence@mttech2021outlook.onmicrosoft.com"]
}

###Create AD Security Group
POST {{funcUrl}}/api/fn-create-ad-security-group?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
    "groupName": "az-poc-test-group2",
    "groupDescription": "v-CSA Group for az-poc-test-group2"    
}

###Run CosmosDB query
POST {{funcUrl}}/api/fn-query-cosmos-db?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "query" : "SELECT * FROM r"  
}

###Get cosmos DB item
GET  {{funcUrl}}/api/fn-get-cosmos-db-item?requestId=sdfd898191&ownerEmail=bablulawrence@gmail.com&code={{funcKey}} HTTP/1.1
Content-Type: application/json

###Get cosmos DB item
POST {{funcUrl}}/api/fn-get-cosmos-db-item?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "requestId" : "sdfd89819",
  "ownerEmail" : "bablulawrence@gmail.com"  
}

###Durable HTTP starter for create resources orchastrator
POST {{funcUrl}}/api/orchestrators/fn-drbl-create-resources-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "requestId" : "sdfd89821",  
  "requestType" : "poc",
  "msxEngagementId" : "7-00012312312",
  "ownerName" : "Bablu Lawrence",
  "ownerEmail" : "bablulawrence@gmail.com",
  "consumption" : 2341,
  "client": "Client1",
  "teamEmails" : "bablulawrence@gmail.com;bablulawrence@gmail.com",    
  "location" : "centralus",
  "requestedDateTime" : "9/07/2021",
  "approvedDateTime" : "9/07/2021"
}

###Durable HTTP starter for database query
POST {{funcUrl}}/api/orchestrators/fn-drbl-query-sql-db-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "server" : "pvlab-fe00b4-synapse.sql.azuresynapse.net",
  "database" : "sqldp01",
  "output" : "json",
  "load": 1,
  "query": "SELECT TOP 20 * FROM Sales.Customer;"
}

###HTTP function for database query
POST {{funcUrl}}/api/fn-get-query-sql-db?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "server" : "pvlab-fe00b4-synapse.sql.azuresynapse.net",
  "database" : "sqldp01",
  "output" : "stats",
  "query": "SELECT TOP 3 * FROM Sales.Customer;"
}

###Durable HTTP starter for delete Purview entities
POST {{funcUrl}}/api/orchestrators/fn-drbl-delete-purview-entities-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "accountName" : "azdemo103mfek9-pv101",
  "query": "*",
  "limit": 100   
}

###Durable HTTP starter for search Purview entities
POST {{funcUrl}}/api/orchestrators/fn-drbl-search-purview-entities-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "accountName" : "azdemo103mfek9-pv101",
  "query": "adworks"   
}

###Durable HTTP starter for VM stop
POST {{funcUrl}}/api/orchestrators/fn-drbl-stop-vm-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId" : "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e" 
}

###Durable HTTP starter for SQL dedicated pool pause
POST {{funcUrl}}/api/orchestrators/fn-drbl-pause-sql-dp-orchstr?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId" : "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e" 
}


###Get SQL Dedicated Pool
POST {{funcUrl}}/api/fn-get-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Pause SQL Dedicated Pool
POST {{funcUrl}}/api/fn-pause-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Resume SQL Dedicated Pool
POST {{funcUrl}}/api/fn-resume-sql-dedicated-pool?code={{funcKey}} HTTP/1.1
Content-Type: application/json

{
  "subscriptionId": "edf6dd9d-7c4a-4bca-a997-945f3d60cf4e",
  "resourceGroupName": "azdemo101-rg-zrlx4",
  "workspaceName": "azsynapsewksxqwjeq",
  "sqlPoolName": "sqldp01"
}

###Publish Event Grid Event
POST {{eventGridUrl}}/api/events?overload=EventGridEvent&api-version=2018-01-01 HTTP/1.1
aeg-sas-key: {{eventGridKey}}
Content-Type: application/json

[
  {
    "id": "b3ccc7e3-c1cb-49bf-b7c8-0d4e60980616",
    "subject": "TestSubject",
    "data": {
      "Property1": "Value1",
      "Property2": "Value2"
    },
    "eventType": "Microsoft.Contoso.TestEvent",
    "eventTime": "2017-12-04T22:06:09.147165Z",
    "dataVersion": "1.0"
  }
]